spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  main:
    web-application-type: reactive
  h2:
    console:
      enabled: true
  sql:
    init:
      platform: h2
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
